version: 0.2

phases:
  install:
    commands:
      - echo Installing Node.js and dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build || echo "No build script defined, skipping build phase"
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
